/**
 * Generated types for this project
 * Auto-generated by `dab sync` - do not edit manually
 */

import type { ProjectContext } from '@botpress-private/dab'

/**
 * Available provisions for this project
 */
export type ProjectProvisions = {
  [key: string]: never
}

/**
 * Available variables for this project
 */
export type ProjectVariables = {
  [key: string]: never
}

/**
 * Available secrets for this project
 */
export type ProjectSecrets = {
  [key: string]: never
}

/**
 * Typed context for this project with precise provision, variable, and secret keys
 */
export type SyncedProjectContext = Extract<ProjectContext, { type: 'static-site' }> & {
  provisions: ProjectProvisions
  variables: ProjectVariables
  secrets: ProjectSecrets
}
